learn_auth/learn_user/basic_app/urls.py
from django.urls import path
from . import views

app_name = 'basic_app'

urlpatterns = [
    path('index', views.index, name='index'),
    path('registration', views.register, name='registration'),
    path('user_login', views.user_login, name='login'),
    path('user_logout', views.user_logout, name='logout'),
]

learn_auth/learn_user/learn_user/urls.py
from django.contrib import admin
from django.urls import path, include
from basic_app import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.index, name='index'),
    path('basic_app/', include('basic_app.urls'))
]

learn_auth/learn_user/basic_app/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.


class UserProfileInfo(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    portfolio_site = models.URLField(blank=True)
    profile_pic = models.ImageField(upload_to='profile_pics', blank=True)

    def __str__(self):
        return self.user.username

learn_auth/learn_user/basic_app/forms.py
from django import forms
from django.contrib.auth.models import User
from .models import UserProfileInfo


class UserForm (forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())

    class Meta:
        model = User
        fields = ('username', 'email', 'password')


class UserProfileInfoForm(forms.ModelForm):

    class Meta:
        model = UserProfileInfo
        fields = ('portfolio_site', 'profile_pic')

learn_auth/learn_user/basic_app/views.py
from django.shortcuts import render
from .forms import UserProfileInfoForm, UserForm
from django.urls import reverse
from django.contrib.auth.decorators import login_required
from django.http import HttpResponseRedirect, HttpResponse
from django.contrib.auth import authenticate, login,logout
# Create your views here.


def index(request):
    return render(request, 'basic_app/index.html')


def special(request):
    return HttpResponse("You Are Logged In")


@login_required
def user_logout(request):
    logout(request)
    return HttpResponseRedirect(reverse('index'))


def user_login(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')

        user = authenticate(username=username, password=password)
        if user:
            if user.is_active:
                login(request, user)
                return HttpResponseRedirect(reverse('index'))
            else:
                return HttpResponse("Account not active")
        else:
            print("NOT LOGGED IN")
            return HttpResponse("NOT LOGGED IN")
    else:
        return render(request, 'basic_app/login.html')


def register(request):
    registered = False

    if request.method == "POST":
        user_form = UserForm(data=request.POST)
        profile_form = UserProfileInfoForm(data=request.POST)

        if user_form.is_valid() and profile_form.is_valid():
            user = user_form.save()
            user.set_password(user.password)
            user.save()

            profile = profile_form.save(commit=False)
            profile.user = user

            if 'profile_pic' in request.FILES:
                profile.profile_pic = request.FILES['profile_pic']

            profile.save()

            registered = True
        else:
            print('ERROR!!')

    else:
        user_form = UserForm()
        profile_form = UserProfileInfoForm()
    return render(request, 'basic_app/registration.html', {'user_form': user_form,
                                                           'profile_form': profile_form, 'registered': registered})

learn_auth/learn_user/templates/basic_app/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
</head>
<body>
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <div class="navbar-header">
      <a class="navbar-brand" href="#">WebSiteName</a>
    </div>
    <ul class="nav navbar-nav">
      <li class="active"><a href="{%url 'index'%}">DJANGO</a></li>
      <li><a href="{%url 'admin:index'%}">Admin</a></li>
        <li><a href="{%url 'basic_app:registration'%}">Register</a></li>
      {%if user.is_authenticated%}
      <li><a href="{%url 'basic_app:logout'%}">logout</a></li>
      {%else%}
        <li><a href="{%url 'basic_app:login'%}">login</a></li>
        {%endif%}
    </ul>
  </div>
</nav>
<div class="container">
    {%block body_block%}
    {%endblock%}
</div>
</body>
</html>

learn_auth/learn_user/templates/basic_app/index.html
<!DOCTYPE html>
{%extends 'basic_app/base.html'%}
    {%block body_block%}
 <div>
     <h1>Django Index</h1>
 </div>
    {%endblock%}

learn_auth/learn_user/templates/basic_app/login.html
<!DOCTYPE html>
{%extends 'basic_app/base.html'%}
{%block body_block%}

<h1 style="margin-left:12px;">Login</h1>
<div class="container">
  <div class="jumbotron">
      <form method="post" action="{%url 'basic_app:login'%}">
            {%csrf_token%}
              <div class="form-group">
                <div class="col-sm-12">
                  <input type="email" class="form-control" name="username" id="email" placeholder="Enter email">
                </div>
              </div>
                    <br>
                    <br>
              <div class="form-group">
                <div class="col-sm-12">
                  <input type="password" class="form-control" name="password" id="pwd" placeholder="Enter password">
                </div>
              </div>
                    <br>
                    <br>
              <div class="form-group">
                <div class="col-sm-offset-5 col-sm-10">
                  <button type="submit" class="btn btn-default">Submit</button>
                </div>
              </div>
        </form>
  </div>
</div>


{%endblock%}

learn_auth/learn_user/templates/basic_app/registration.html
<!DOCTYPE html>
{%extends 'basic_app/base.html'%}
{%load static%}
{%block body_block%}
 <div>
     {%if registered%}
     <h1>Django Login, Registration</h1>
     {%else%}
     <h1>Register First</h1>
     <h3>fill out the following form</h3>
     <form method="post">
         {{user_form.as_p}}
         {{profile_form.as_p}}
         {%csrf_token%}
         <input type="submit" value="Register">
     </form>
     {%endif%}

 </div>
    {%endblock%}